all:
	gcc -I../../libpng/include/libpng16 -L../../libpng/lib -lpng16 -o extractor sprite_extractor.c image_gen.c
	gcc -I../../libpng/include/libpng16 -L../../libpng/lib -lpng16 -o conventer sprite_conventer.c image_gen.c
